%% input
clc
clear
load('input_var_for_example_Yangtze.mat', ...
    'EWHobs', ...
    'EWHtrue_ini',...
    'GauR', ...
    'Lat_Data', ...
    'Lon_Data',...
    'RMSE_threshold', ...
    'grdarea',...
    'iteration_threshold', ...
    'land_mask',...
    'maxSHod', ...
    'model_yzt', ...
    'model_mask',...
    'box_mask')
%% compute
constrain_ = 3; %######choose constrain type#####
switch constrain_
    case 1 %######constrained FM######
        target_mask = model_mask;
    case 2 %######unconstrained FM, extended Yangtze basin, Lat:(20,40),Lon:(85,125)######
        target_mask = box_mask;
    case 3 %######unconstrained FM, Yangtze basin######
        target_mask = land_mask;
end

[EWHtrue_k_c,EWHpred_k_c,RMSE_k] = ForwModl_gzh(EWHobs,...
    EWHtrue_ini,...
    Lat_Data,...
    Lon_Data,...
    land_mask,...
    grdarea,...
    target_mask,...
    RMSE_threshold,...
    iteration_threshold,...
    GauR,...
    maxSHod);
switch constrain_
    case 1
        disp('saving constrainedFM(Yangtze mask) output')
        save('constrainedFM.mat','EWHtrue_k_c','EWHpred_k_c','RMSE_k')
    case 2
        disp('saving unconstrainedFM(box mask) output')
        save('unconstrainedFM.mat','EWHtrue_k_c','EWHpred_k_c','RMSE_k')
    case 3
        disp('saving unconstrainedFM(land mask) output')
        save('unconstrainedFM.mat','EWHtrue_k_c','EWHpred_k_c','RMSE_k')
end
%% RMSE comparison
figure;
set(gcf,'units','cent','position',[2,2,24,12]);
load('constrainedFM.mat','RMSE_k')
plot(RMSE_k,'r.-','markersize',12,'linewidth',1);
hold on;
load('unconstrainedFM.mat','RMSE_k')
plot(RMSE_k,'b.-','markersize',12,'linewidth',1);
grid on;
xlabel('Number of iterations')
ylabel('RMSE (Gt)')
xlim([1,50])
legend('show',{'constrained','unconstrained'},'location','ne')
%% iteration comparison
example_func_iteration_comparison('cons',1)
%% No.50 iteration comparison
example_func_iter50_comparison('uncons',2)
